# Setup
title:               Pitaya
tagline:             'A Cook then A Queen'
description:         'The Kingdom of Pitaya is a nation ruled by a cook. Here we have all the amazing things one dreams about.'
url:                 https://pty-gh.github.io
baseurl:             /Kingdom
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Big Wang
  url:               https://github.com/PTY-GH/
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
